//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dish
    {
        public int DishID { get; set; }
        [Display(Name = "Dish Name")]
        public string DishName { get; set; }
        [Display(Name = "Dish Description")]
        public string DishDescription { get; set; }
        [Display(Name = "Dish Price")]
        public Nullable<decimal> DishPrice { get; set; }
        public Nullable<int> CuisineID { get; set; }

        public virtual Cuisine Cuisine { get; set; }
    }
}
