//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class News
    {
        public int NewsID { get; set; }
        [Display(Name = "Headlines")]
        [Required(ErrorMessage = "Headline is Required")]
        public string NewsHeadline { get; set; }
        [Display(Name = "News Description")]
        [Required(ErrorMessage = "Description is Required")]
        public string NewsDescription { get; set; }
        [Display(Name = "Date of Release")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Date is required")]
        public Nullable<System.DateTime> NewsDate { get; set; }

        public string Author { get; set; }
    }
}
